import type {
  AcquisitionRow,
  AnalyticsInsights,
  DropOffRow,
  PagePerformanceRow,
} from "@/types";
import {
  formatCompact,
  formatDuration,
  formatNumber,
  formatPercent,
  truncatePath,
} from "@/lib/format";

/**
 * Automated analytics narrative.
 *
 * ## What this does, and what it deliberately does not
 *
 * These insights are generated by fixed rules, not by a language model. That is
 * a feature: the output is reproducible, costs nothing, and cannot invent a
 * fact that is not in the data.
 *
 * The rules state **what changed and which segment accounted for it**. They
 * never state *why*. The difference matters more than it sounds. "Traffic fell
 * 22%, and Organic Search accounted for 81% of the drop" is arithmetic — it is
 * checkable, and it points at where to look. "Traffic fell because of the
 * homepage redesign" is a guess dressed as a finding: analytics records no
 * deploys, no copy changes and no algorithm updates, so nothing in the data can
 * support it. One wrong guess of that kind costs the reader their trust in
 * every true statement sitting next to it, so this file does not make them.
 *
 * Recommendations are allowed, because a recommendation is an action to
 * consider rather than a claim about the past. Each one is tied to the specific
 * number that triggered it.
 */

export type InsightTone = "positive" | "negative" | "neutral";

export interface AnalyticsNarrative {
  id: string;
  /** One sentence: the change itself. */
  headline: string;
  /** Which segment accounted for it. Never a cause. */
  detail: string;
  tone: InsightTone;
  /** What to do next. Omitted when there is nothing useful to suggest. */
  recommendation?: string;
  evidence: { label: string; value: string }[];
}

/* -------------------------------------------------------------------------- */
/*  Thresholds                                                                 */
/* -------------------------------------------------------------------------- */

/** Relative change below this is noise, not news. */
const MIN_CHANGE = 0.05;

/** Absolute floors — percentages on tiny numbers are meaningless. */
const MIN_SESSIONS = 50;
const MIN_PAGE_VIEWS = 100;

/** A channel above this share is a concentration risk worth naming. */
const CONCENTRATION = 0.7;

/* -------------------------------------------------------------------------- */
/*  Helpers                                                                    */
/* -------------------------------------------------------------------------- */

function change(current: number, previous: number): number {
  if (previous === 0) return current === 0 ? 0 : 1;
  return (current - previous) / previous;
}

function pct(fraction: number): string {
  return `${Math.abs(Math.round(fraction * 100))}%`;
}

function direction(delta: number): string {
  return delta > 0 ? "increased" : "decreased";
}

/**
 * Which segment accounted for most of a total change.
 *
 * Contribution is measured as each row's share of the *net* movement, so a
 * channel that grew while the total fell correctly reads as offsetting rather
 * than contributing. Returns nothing when the movement is spread evenly — in
 * that case naming a leader would imply a concentration that is not there.
 */
function topContributor(
  rows: AcquisitionRow[],
  totalDelta: number,
): { row: AcquisitionRow; delta: number; share: number } | undefined {
  if (rows.length === 0 || totalDelta === 0) return undefined;

  const scored = rows
    .map((row) => ({ row, delta: row.sessions - row.prevSessions }))
    // Only rows moving the same way as the total can be said to have driven it.
    .filter((r) => (totalDelta > 0 ? r.delta > 0 : r.delta < 0))
    .sort((a, b) => Math.abs(b.delta) - Math.abs(a.delta));

  const leader = scored[0];
  if (!leader) return undefined;

  const share = Math.abs(leader.delta) / Math.abs(totalDelta);
  // Below a third, no single segment meaningfully led the change.
  if (share < 0.33) return undefined;

  return { ...leader, share: Math.min(1, share) };
}

/* -------------------------------------------------------------------------- */
/*  Rules                                                                      */
/* -------------------------------------------------------------------------- */

function trafficInsight(data: AnalyticsInsights): AnalyticsNarrative | undefined {
  const { engagement: now, previousEngagement: before, channels } = data;
  // Both windows must carry real traffic. Comparing against an empty previous
  // period yields "+100%", which reads as doubling when it actually means the
  // property was not collecting data yet — see `noBaselineInsight`.
  if (now.sessions < MIN_SESSIONS || before.sessions < MIN_SESSIONS) return undefined;

  const delta = change(now.sessions, before.sessions);
  if (Math.abs(delta) < MIN_CHANGE) return undefined;

  const netDelta = now.sessions - before.sessions;
  const leader = topContributor(channels, netDelta);
  const up = delta > 0;

  return {
    id: "traffic",
    headline: `Sessions ${direction(delta)} ${pct(delta)}, from ${formatCompact(before.sessions)} to ${formatCompact(now.sessions)}.`,
    detail: leader
      ? `${leader.row.label} accounted for ${pct(leader.share)} of the ${up ? "increase" : "decrease"} — ${up ? "+" : ""}${formatNumber(leader.delta)} sessions on its own.`
      : `The change was spread across channels, with no single one accounting for most of it.`,
    tone: up ? "positive" : "negative",
    recommendation: up
      ? leader
        ? `Find what is working in ${leader.row.label} and extend it. Check which landing pages absorbed the extra sessions and whether they convert as well as the rest of the site.`
        : `Growth is broad rather than concentrated. Confirm the site can carry it — check that your highest-traffic pages still hold engagement at this volume.`
      : leader
        ? `Investigate ${leader.row.label} specifically before anything else — it is where the loss is concentrated. Compare its landing pages against the previous period to see whether the decline is site-wide or confined to a few entry points.`
        : `The decline is spread evenly, which points at something site-wide rather than one channel. Check seasonality against the same period last year before treating it as a regression.`,
    evidence: [
      { label: "Sessions", value: `${formatCompact(before.sessions)} → ${formatCompact(now.sessions)}` },
      { label: "Users", value: `${formatCompact(before.users)} → ${formatCompact(now.users)}` },
      ...(leader ? [{ label: "Largest mover", value: leader.row.label }] : []),
    ],
  };
}

/**
 * The previous window has no data to compare against.
 *
 * Emitted instead of the change-based insights, which would otherwise report
 * every metric as "+100%" — technically what the arithmetic says, and a
 * complete misreading of what happened.
 */
function noBaselineInsight(data: AnalyticsInsights): AnalyticsNarrative | undefined {
  const { engagement: now, previousEngagement: before } = data;
  if (now.sessions < MIN_SESSIONS) return undefined;
  if (before.sessions >= MIN_SESSIONS) return undefined;

  return {
    id: "no-baseline",
    headline: "There is no previous period to compare against.",
    detail: `This window recorded ${formatCompact(now.sessions)} sessions, but the preceding window recorded ${before.sessions === 0 ? "none" : formatCompact(before.sessions)}. Period-over-period changes are omitted rather than shown as growth from zero.`,
    tone: "neutral",
    recommendation:
      "This usually means Analytics was connected part-way through, or the tag only started firing recently. Comparisons become meaningful once a full previous window has been collected.",
    evidence: [
      { label: "This period", value: formatCompact(now.sessions) },
      { label: "Previous", value: before.sessions === 0 ? "No data" : formatCompact(before.sessions) },
    ],
  };
}

function engagementInsight(data: AnalyticsInsights): AnalyticsNarrative | undefined {
  const { engagement: now, previousEngagement: before, pages } = data;
  if (now.sessions < MIN_SESSIONS || before.sessions < MIN_SESSIONS) return undefined;

  const delta = change(now.engagementRate, before.engagementRate);
  if (Math.abs(delta) < MIN_CHANGE) return undefined;

  const down = delta < 0;
  // Name the busiest weak page — where a fix would move the site-wide number most.
  const weakest = [...pages]
    .filter((p) => p.views >= MIN_PAGE_VIEWS)
    .sort((a, b) => a.engagementRate * a.views - b.engagementRate * b.views)[0];

  return {
    id: "engagement",
    headline: `Engagement rate ${direction(delta)} ${pct(delta)}, from ${formatPercent(before.engagementRate, 1)} to ${formatPercent(now.engagementRate, 1)}.`,
    detail: down
      ? weakest
        ? `The largest concentration of disengaged traffic is ${truncatePath(weakest.page, 40)} — ${formatCompact(weakest.views)} views at ${formatPercent(weakest.engagementRate, 1)} engagement.`
        : `No single page dominates the disengaged traffic; the shift is spread across the site.`
      : `Visitors are staying longer and viewing more per session than they were.`,
    tone: down ? "negative" : "positive",
    recommendation: down
      ? `${weakest ? `Start with ${truncatePath(weakest.page, 40)} — it has the most traffic to recover. ` : ""}Check whether page-load time, intrusive interstitials, or a mismatch between the entry keyword and the content explain the drop-off. Compare mobile against desktop; the two often diverge sharply.`
      : `Whatever changed is working. Identify which pages improved most and apply the same treatment to your weakest entry points.`,
    evidence: [
      { label: "Engagement rate", value: `${formatPercent(before.engagementRate, 1)} → ${formatPercent(now.engagementRate, 1)}` },
      { label: "Bounce rate", value: `${formatPercent(before.bounceRate, 1)} → ${formatPercent(now.bounceRate, 1)}` },
      { label: "Views / session", value: `${before.viewsPerSession.toFixed(1)} → ${now.viewsPerSession.toFixed(1)}` },
    ],
  };
}

function dropOffInsight(data: AnalyticsInsights): AnalyticsNarrative | undefined {
  const worst: DropOffRow | undefined = data.dropOff[0];
  if (!worst || worst.sessions < MIN_SESSIONS) return undefined;
  if (worst.bounceRate < 0.5) return undefined;

  const totalLost = data.dropOff.reduce((sum, r) => sum + r.lostSessions, 0);
  const share = totalLost === 0 ? 0 : worst.lostSessions / totalLost;

  return {
    id: "drop-off",
    headline: `${truncatePath(worst.page, 42)} loses the most sessions of any entry point — ${formatCompact(worst.lostSessions)} of ${formatCompact(worst.sessions)} leave without engaging.`,
    detail: `That is ${formatPercent(worst.bounceRate, 1)} of its sessions, and ${pct(share)} of all disengaged entries across the site.`,
    tone: "negative",
    recommendation: `This page is the single highest-volume place to intervene. Check that it delivers what the referring channel promised, that the primary action is visible without scrolling, and that it loads quickly on mobile.`,
    evidence: [
      { label: "Sessions", value: formatNumber(worst.sessions) },
      { label: "Bounce rate", value: formatPercent(worst.bounceRate, 1) },
      { label: "Avg. duration", value: formatDuration(Math.round(worst.avgSessionDuration)) },
    ],
  };
}

function conversionInsight(data: AnalyticsInsights): AnalyticsNarrative | undefined {
  const c = data.conversions;

  if (c.notConfigured) {
    return {
      id: "conversions",
      headline: "No key events are configured in Google Analytics.",
      detail:
        "Nothing on this property is marked as a key event, so conversions cannot be measured — this is a setup gap, not a result of zero conversions.",
      tone: "neutral",
      recommendation:
        "In GA4, open Admin → Events and toggle “Mark as key event” on the actions that matter — a form submit, a signup, a purchase. Data collects from that point forward and is not backfilled, so the sooner it is set the sooner this section becomes useful.",
      evidence: [{ label: "Key events", value: "Not configured" }],
    };
  }

  const delta = change(c.keyEvents, c.prevKeyEvents);
  if (Math.abs(delta) < MIN_CHANGE) return undefined;

  const top = c.events[0];
  const up = delta > 0;

  return {
    id: "conversions",
    headline: `Key events ${direction(delta)} ${pct(delta)}, from ${formatNumber(c.prevKeyEvents)} to ${formatNumber(c.keyEvents)}.`,
    detail: top
      ? `${top.eventName} is the largest single event at ${formatNumber(top.keyEvents)} (${top.trend >= 0 ? "+" : ""}${pct(top.trend)}).`
      : `No individual event dominates the total.`,
    tone: up ? "positive" : "negative",
    recommendation: up
      ? `Trace which channel and landing pages produced the additional key events, and weight your effort toward them.`
      : `Check whether the fall tracks the traffic change or is independent of it. If sessions held steady while key events fell, the problem is on the page rather than in acquisition.`,
    evidence: [
      { label: "Key events", value: `${formatNumber(c.prevKeyEvents)} → ${formatNumber(c.keyEvents)}` },
      { label: "Session rate", value: formatPercent(c.keyEventRate, 2) },
      ...(top ? [{ label: "Top event", value: top.eventName }] : []),
    ],
  };
}

function concentrationInsight(data: AnalyticsInsights): AnalyticsNarrative | undefined {
  const leader = data.channels[0];
  if (!leader || leader.share < CONCENTRATION) return undefined;
  if (data.engagement.sessions < MIN_SESSIONS) return undefined;

  return {
    id: "concentration",
    headline: `${leader.label} supplies ${formatPercent(leader.share, 0)} of all sessions.`,
    detail: `The next largest channel is ${data.channels[1]?.label ?? "none"} at ${formatPercent(data.channels[1]?.share ?? 0, 0)}. A single channel carrying this much traffic is a concentration risk.`,
    tone: "neutral",
    recommendation: `A ranking change or algorithm update in ${leader.label} would take most of the site's traffic with it. Build a second channel deliberately — email, referral or direct — so the site is not dependent on one source staying healthy.`,
    evidence: data.channels.slice(0, 3).map((c) => ({
      label: c.label,
      value: formatPercent(c.share, 0),
    })),
  };
}

function topPageInsight(data: AnalyticsInsights): AnalyticsNarrative | undefined {
  const eligible = data.pages.filter((p) => p.views >= MIN_PAGE_VIEWS);
  const best: PagePerformanceRow | undefined = eligible[0];
  if (!best) return undefined;

  // The table ranks every page above the provider's floor; this rule applies a
  // higher one. Without saying so, the two disagree whenever a small page tops
  // the table — the card would name a different "best" than the list beside it.
  const qualified = eligible.length < data.pages.length;

  return {
    id: "top-page",
    headline: `${truncatePath(best.page, 42)} is the strongest performing page${qualified ? ` with over ${MIN_PAGE_VIEWS} views` : ""}, scoring ${best.score}/100.`,
    detail: `${formatPercent(best.engagementRate, 1)} engagement across ${formatCompact(best.views)} views, holding attention for ${formatDuration(Math.round(best.avgEngagementTime))} on average.`,
    tone: "positive",
    recommendation: `Treat this page as the template. Compare its structure, length and internal linking against your weakest pages, and copy what is working rather than guessing at fixes.`,
    evidence: [
      { label: "Views", value: formatCompact(best.views) },
      { label: "Engagement", value: formatPercent(best.engagementRate, 1) },
      { label: "Avg. time", value: formatDuration(Math.round(best.avgEngagementTime)) },
    ],
  };
}

function worstPageInsight(data: AnalyticsInsights): AnalyticsNarrative | undefined {
  const candidates = data.pages.filter((p) => p.views >= MIN_PAGE_VIEWS);
  const worst = candidates[candidates.length - 1];
  // Only worth a card when it is meaningfully worse than the best.
  if (!worst || candidates.length < 3 || worst.score >= 50) return undefined;

  return {
    id: "worst-page",
    headline: `${truncatePath(worst.page, 42)} is the weakest performing page with real traffic, scoring ${worst.score}/100.`,
    detail: `It draws ${formatCompact(worst.views)} views but holds only ${formatPercent(worst.engagementRate, 1)} engagement, averaging ${formatDuration(Math.round(worst.avgEngagementTime))} per view.`,
    tone: "negative",
    recommendation: `Traffic is arriving and leaving. Decide whether the page is failing to deliver on what brought people there, or whether it attracts the wrong audience — then either rewrite it against the intent it actually receives, or redirect it into a stronger page on the topic.`,
    evidence: [
      { label: "Views", value: formatCompact(worst.views) },
      { label: "Engagement", value: formatPercent(worst.engagementRate, 1) },
      { label: "Bounce", value: formatPercent(worst.bounceRate, 1) },
    ],
  };
}

function audienceInsight(data: AnalyticsInsights): AnalyticsNarrative | undefined {
  const returning = data.audience.find((a) => a.label === "Returning");
  const fresh = data.audience.find((a) => a.label === "New");
  if (!returning || !fresh || data.engagement.users < MIN_SESSIONS) return undefined;
  if (returning.share >= 0.15) return undefined;

  return {
    id: "audience",
    headline: `Returning visitors are only ${formatPercent(returning.share, 0)} of the audience.`,
    detail: `${formatPercent(fresh.share, 0)} of users are new. Returning visitors engage at ${formatPercent(returning.engagementRate, 1)} against ${formatPercent(fresh.engagementRate, 1)} for new ones.`,
    tone: "neutral",
    recommendation: `Almost everyone arrives once and does not come back. If repeat visits matter for this site, give people a reason to return — a newsletter, saved state, or a series that continues — rather than buying the same first visit repeatedly.`,
    evidence: [
      { label: "New", value: formatPercent(fresh.share, 0) },
      { label: "Returning", value: formatPercent(returning.share, 0) },
    ],
  };
}

/* -------------------------------------------------------------------------- */
/*  Engine                                                                     */
/* -------------------------------------------------------------------------- */

const RULES = [
  noBaselineInsight,
  trafficInsight,
  engagementInsight,
  conversionInsight,
  dropOffInsight,
  worstPageInsight,
  concentrationInsight,
  topPageInsight,
  audienceInsight,
];

/**
 * Run every rule. Order is the display order: what changed, then what is
 * losing traffic, then what is working.
 */
export function buildNarrative(data: AnalyticsInsights): AnalyticsNarrative[] {
  return RULES.map((rule) => rule(data)).filter(
    (insight): insight is AnalyticsNarrative => insight !== undefined,
  );
}
